export const FIND_FALCONE_SUCCESS = 'FIND_FALCONE_SUCCESS';
export const FIND_FALCONE_ERROR = 'FIND_FALCONE_ERROR';
export const FIND_FALCONE_SERVER_ERROR = 'FIND_FALCONE_SERVER_ERROR';
export const RESET = 'RESET';
export const RESET_BACK = 'RESET_BACK';

